version: '3'
services:
  jenkins:
    image: rwlaub/jenkins
    environment:
      - GITHUB_ID=mikehunacek
      - DOCKERHUB_ID=mhunacek
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
